[package]
name = "astrorigin"
version = "0.1.0"
description = "星原手记 - Genshin Impact / Star Rail Companion App"
authors = ["dakubo"]
edition = "2021"

[lib]
name = "astrorigin_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "astrorigin"
path = "src/main.rs"

[dependencies]
tauri = { version = "2.2", features = [] }
tauri-plugin-shell = "2"
tokio = { version = "1", features = ["rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.25"
anyhow = "1"
chrono = "0.4"
image = "0.25"
sysinfo = "0.33"
windows = { version = "0.58", features = [
    "Foundation_Collections",
    "Globalization",
    "Graphics_Imaging",
    "Media_Ocr",
    "Storage_Streams",
    "UI_Notifications",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.release]
strip = true
lto = true
codegen-units = 1
